#include "renderer.h"


RenderContext_t *initRenderContext(void)
{
	RenderContext_t *ctx;

	SDLX_InitDefault();

	ctx = SDL_calloc(1, sizeof(*ctx));
	ctx->display = SDLX_DisplayGet();

	SDLX_KeyMap(SDLX_KEYBOARDTYPE, SDL_SCANCODE_LEFT, KEY_LEFT);
	SDLX_KeyMap(SDLX_KEYBOARDTYPE, SDL_SCANCODE_LEFT, KEY_LEFT);

	SDLX_KeyMap(SDLX_KEYBOARDTYPE, SDL_SCANCODE_LEFT, KEY_RIGHT);
	SDLX_KeyMap(SDLX_KEYBOARDTYPE, SDL_SCANCODE_LEFT, KEY_RIGHT);

	SDLX_KeyMap(SDLX_KEYBOARDTYPE, SDL_SCANCODE_LEFT, KEY_UP);
	SDLX_KeyMap(SDLX_KEYBOARDTYPE, SDL_SCANCODE_LEFT, KEY_UP);

	SDLX_KeyMap(SDLX_KEYBOARDTYPE, SDL_SCANCODE_LEFT, KEY_DOWN);
	SDLX_KeyMap(SDLX_KEYBOARDTYPE, SDL_SCANCODE_LEFT, KEY_DOWN);

	SDLX_KeyMap(SDLX_KEYBOARDTYPE, SDL_SCANCODE_LEFT, KEY_ZOOM);
	SDLX_KeyMap(SDLX_KEYBOARDTYPE, SDL_SCANCODE_LEFT, KEY_MODE);

	return ctx;
}
